name: Notify Discord

on:
  push:
    #branches:
    #  - main  # or whatever branch you want

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Send message to Discord
        uses: appleboy/discord-action@master
        with:
          webhook_id: ${{ secrets.DISCORD_WEBHOOK_URL }}
          username: GitHub Actions
          message: |
            🚀 A new push was made to the **${{ github.ref_name }}** branch!
            📦 Commit: ${{ github.event.head_commit.message }}
            👤 Author: ${{ github.event.head_commit.author.name }}
